---
- name: Upgrade everything on the cluster.
  hosts: cluster
  become: true

  tasks:
    - name: Upgrade all software.
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Check if a reboot is required.
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      apt:
        autoremove: yes
